-- 완료함 검색 
use Common
select * from [IM].[VIEW_USER] where user_name like '이우근'
exec CM.usp_MemberMapping_select @id='28226'


use EWF
SELECT
		EXIST_ISURGENT,
		UPPER(ATTACH_EXTENSION) as ATTACH_EXTENSION,
		EXIST_COMMENT,
		EXIST_REF_DOCUMENT,
		NAME as DOC_NAME,
		REPLACE(replace(subject, char(13),''), char(10),''),
		CREATOR,
		CREATOR_DEPT,
		EXIST_ATTACH,
		CREATOR_ID,
		PARENT_OID,
		FORM_ID,
		CURRENT_USER_NAME,
		CURRENT_DEPT_NAME,
		CURRENT_LEVEL,
		b.LOCATION,
		b.COMPLETED_DATE as CREATE_DATE,
		a.COMPLETED_DATE as COMPLETED_DATE,
		b.OPEN_YN,
		b.OID as WORK_ITEM_OID,
		b.PROCESS_INSTANCE_OID,
		b.WKITEM_ID,
		ROW_NUMBER() OVER ( ORDER BY b.CREATE_DATE desc) AS RowNum, 
		COUNT(*) OVER ( ) AS [RowCount],
		DOC_NUMBER
	FROM WF.PROCESS_INSTANCE a
		INNER JOIN WF.WORK_ITEM_CMPL b ON A.OID = b.PROCESS_INSTANCE_OID 
		WHERE B.DELETE_DATE is null AND b.PARTICIPANT_ID = '28226_CO'

