
SELECT 
F.SUGGESTDATE
,F.CREATOR_DEPT
,F.CREATOR
,F.SUBJECT
,PI.STATE
,ADD_CHECK_1	
,ADD_CHECK_2	
,ADD_CHECK_3	
,ADD_CHECK_4	
,ADD_CHECK_5	
,ADD_CHECK_6
,ADD_CHECK_7
,ADD_CHECK_8
,ADD_CHECK_9
,ADD_CHECK_10
,ADD_ANSWER_1	
,ADD_ANSWER_2	
,ADD_ANSWER_3	
,ADD_ANSWER_4	
,ADD_ANSWER_5	
,ADD_ANSWER_6	
,ADD_ANSWER_7	
,ADD_ANSWER_8	
,ADD_ANSWER_9	
,ADD_ANSWER_10
,ADD_UPGRADE_1
,ADD_UPGRADE_2
,ADD_UPGRADE_3
,ADD_UPGRADE_4
,ADD_UPGRADE_5
,ADD_UPGRADE_6
,ADD_UPGRADE_7
,ADD_UPGRADE_8
,ADD_UPGRADE_9
,ADD_UPGRADE_10
FROM [WF].[FORM_YD6F5A0765A154DA99AAFA2E51FD4854F]  AS F
LEFT JOIN [WF].[PROCESS_INSTANCE] AS PI
ON F.PROCESS_ID = PI.OID
WHERE PI.STATE is not null
ORDER BY SUGGESTDATE 
