.$env:exchangeinstallpath\bin\remoteexchange.ps1
connect-exchangeserver -Auto

NEW-MailboxExportRequest	-Mailbox	nicet0	-FilePath	\\localhost\D$\음료\nicet0.pst
NEW-MailboxExportRequest	-Mailbox	khjhm	-FilePath	\\localhost\D$\음료\khjhm.pst
NEW-MailboxExportRequest	-Mailbox	ksh8803	-FilePath	\\localhost\D$\음료\ksh8803.pst
NEW-MailboxExportRequest	-Mailbox	koboksu	-FilePath	\\localhost\D$\음료\koboksu.pst
NEW-MailboxExportRequest	-Mailbox	thurnder19	-FilePath	\\localhost\D$\음료\thurnder19.pst
NEW-MailboxExportRequest	-Mailbox	navy410v	-FilePath	\\localhost\D$\음료\navy410v.pst
NEW-MailboxExportRequest	-Mailbox	sxdd	-FilePath	\\localhost\D$\음료\sxdd.pst
NEW-MailboxExportRequest	-Mailbox	kkwakchan	-FilePath	\\localhost\D$\음료\kkwakchan.pst
NEW-MailboxExportRequest	-Mailbox	mkkoo	-FilePath	\\localhost\D$\음료\mkkoo.pst
NEW-MailboxExportRequest	-Mailbox	cksis	-FilePath	\\localhost\D$\음료\cksis.pst
NEW-MailboxExportRequest	-Mailbox	ksh1023	-FilePath	\\localhost\D$\음료\ksh1023.pst
NEW-MailboxExportRequest	-Mailbox	espoir	-FilePath	\\localhost\D$\음료\espoir.pst
NEW-MailboxExportRequest	-Mailbox	goldpants	-FilePath	\\localhost\D$\음료\goldpants.pst
NEW-MailboxExportRequest	-Mailbox	eunjik	-FilePath	\\localhost\D$\음료\eunjik.pst
NEW-MailboxExportRequest	-Mailbox	rladkacjf	-FilePath	\\localhost\D$\음료\rladkacjf.pst
NEW-MailboxExportRequest	-Mailbox	donghwa	-FilePath	\\localhost\D$\음료\donghwa.pst
NEW-MailboxExportRequest	-Mailbox	mwkim	-FilePath	\\localhost\D$\음료\mwkim.pst
NEW-MailboxExportRequest	-Mailbox	kboss77	-FilePath	\\localhost\D$\음료\kboss77.pst
NEW-MailboxExportRequest	-Mailbox	sckim	-FilePath	\\localhost\D$\음료\sckim.pst
NEW-MailboxExportRequest	-Mailbox	mezurashii	-FilePath	\\localhost\D$\음료\mezurashii.pst
NEW-MailboxExportRequest	-Mailbox	fierly	-FilePath	\\localhost\D$\음료\fierly.pst
NEW-MailboxExportRequest	-Mailbox	shina	-FilePath	\\localhost\D$\음료\shina.pst
NEW-MailboxExportRequest	-Mailbox	shinykim21	-FilePath	\\localhost\D$\음료\shinykim21.pst
NEW-MailboxExportRequest	-Mailbox	lamb	-FilePath	\\localhost\D$\음료\lamb.pst
NEW-MailboxExportRequest	-Mailbox	canufeelme	-FilePath	\\localhost\D$\음료\canufeelme.pst
NEW-MailboxExportRequest	-Mailbox	mars0724	-FilePath	\\localhost\D$\음료\mars0724.pst
NEW-MailboxExportRequest	-Mailbox	upnya0911	-FilePath	\\localhost\D$\음료\upnya0911.pst
NEW-MailboxExportRequest	-Mailbox	kimyj86	-FilePath	\\localhost\D$\음료\kimyj86.pst
NEW-MailboxExportRequest	-Mailbox	qkqh87	-FilePath	\\localhost\D$\음료\qkqh87.pst
NEW-MailboxExportRequest	-Mailbox	jmkim	-FilePath	\\localhost\D$\음료\jmkim.pst
NEW-MailboxExportRequest	-Mailbox	jokim	-FilePath	\\localhost\D$\음료\jokim.pst
NEW-MailboxExportRequest	-Mailbox	kceer	-FilePath	\\localhost\D$\음료\kceer.pst
NEW-MailboxExportRequest	-Mailbox	ikarus97	-FilePath	\\localhost\D$\음료\ikarus97.pst
NEW-MailboxExportRequest	-Mailbox	chilsung2	-FilePath	\\localhost\D$\음료\chilsung2.pst
NEW-MailboxExportRequest	-Mailbox	chkim	-FilePath	\\localhost\D$\음료\chkim.pst
NEW-MailboxExportRequest	-Mailbox	dittohead	-FilePath	\\localhost\D$\음료\dittohead.pst
NEW-MailboxExportRequest	-Mailbox	tjkim1	-FilePath	\\localhost\D$\음료\tjkim1.pst
NEW-MailboxExportRequest	-Mailbox	kimth	-FilePath	\\localhost\D$\음료\kimth.pst
NEW-MailboxExportRequest	-Mailbox	hoon0110	-FilePath	\\localhost\D$\음료\hoon0110.pst
NEW-MailboxExportRequest	-Mailbox	ggacjin	-FilePath	\\localhost\D$\음료\ggacjin.pst
NEW-MailboxExportRequest	-Mailbox	Jun-35	-FilePath	\\localhost\D$\음료\1839149.pst
NEW-MailboxExportRequest	-Mailbox	ccc4834	-FilePath	\\localhost\D$\음료\ccc4834.pst
NEW-MailboxExportRequest	-Mailbox	ghksl75	-FilePath	\\localhost\D$\음료\ghksl75.pst
NEW-MailboxExportRequest	-Mailbox	akrnfk0410	-FilePath	\\localhost\D$\음료\akrnfk0410.pst
NEW-MailboxExportRequest	-Mailbox	smileyh	-FilePath	\\localhost\D$\음료\smileyh.pst
NEW-MailboxExportRequest	-Mailbox	lulu0303	-FilePath	\\localhost\D$\음료\lulu0303.pst
NEW-MailboxExportRequest	-Mailbox	ryu	-FilePath	\\localhost\D$\음료\ryu.pst
NEW-MailboxExportRequest	-Mailbox	jkryou	-FilePath	\\localhost\D$\음료\jkryou.pst
NEW-MailboxExportRequest	-Mailbox	msj	-FilePath	\\localhost\D$\음료\msj.pst
NEW-MailboxExportRequest	-Mailbox	pkmin	-FilePath	\\localhost\D$\음료\pkmin.pst
NEW-MailboxExportRequest	-Mailbox	skpark14	-FilePath	\\localhost\D$\음료\skpark14.pst
NEW-MailboxExportRequest	-Mailbox	karidark	-FilePath	\\localhost\D$\음료\karidark.pst
NEW-MailboxExportRequest	-Mailbox	blackyoshi	-FilePath	\\localhost\D$\음료\blackyoshi.pst
NEW-MailboxExportRequest	-Mailbox	yhpark	-FilePath	\\localhost\D$\음료\yhpark.pst
NEW-MailboxExportRequest	-Mailbox	ygpark	-FilePath	\\localhost\D$\음료\ygpark.pst
NEW-MailboxExportRequest	-Mailbox	lrs11	-FilePath	\\localhost\D$\음료\lrs11.pst
NEW-MailboxExportRequest	-Mailbox	wpssj	-FilePath	\\localhost\D$\음료\wpssj.pst
NEW-MailboxExportRequest	-Mailbox	bzy3411	-FilePath	\\localhost\D$\음료\bzy3411.pst
NEW-MailboxExportRequest	-Mailbox	pjy0279	-FilePath	\\localhost\D$\음료\pjy0279.pst
NEW-MailboxExportRequest	-Mailbox	parkchulsoon	-FilePath	\\localhost\D$\음료\parkchulsoon.pst
NEW-MailboxExportRequest	-Mailbox	dreamholic	-FilePath	\\localhost\D$\음료\dreamholic.pst
NEW-MailboxExportRequest	-Mailbox	minahbae	-FilePath	\\localhost\D$\음료\minahbae.pst
NEW-MailboxExportRequest	-Mailbox	bong7925	-FilePath	\\localhost\D$\음료\bong7925.pst
NEW-MailboxExportRequest	-Mailbox	hansagong	-FilePath	\\localhost\D$\음료\hansagong.pst
NEW-MailboxExportRequest	-Mailbox	mydandism	-FilePath	\\localhost\D$\음료\mydandism.pst
NEW-MailboxExportRequest	-Mailbox	aroha87	-FilePath	\\localhost\D$\음료\aroha87.pst
NEW-MailboxExportRequest	-Mailbox	suyanzhi	-FilePath	\\localhost\D$\음료\suyanzhi.pst
NEW-MailboxExportRequest	-Mailbox	ms7328	-FilePath	\\localhost\D$\음료\ms7328.pst
NEW-MailboxExportRequest	-Mailbox	curiosong	-FilePath	\\localhost\D$\음료\curiosong.pst
NEW-MailboxExportRequest	-Mailbox	sis10	-FilePath	\\localhost\D$\음료\sis10.pst
NEW-MailboxExportRequest	-Mailbox	songhadong	-FilePath	\\localhost\D$\음료\songhadong.pst
NEW-MailboxExportRequest	-Mailbox	se2317	-FilePath	\\localhost\D$\음료\se2317.pst
NEW-MailboxExportRequest	-Mailbox	hjsong2	-FilePath	\\localhost\D$\음료\hjsong2.pst
NEW-MailboxExportRequest	-Mailbox	20130694	-FilePath	\\localhost\D$\음료\20130694.pst
NEW-MailboxExportRequest	-Mailbox	sddol25	-FilePath	\\localhost\D$\음료\sddol25.pst
NEW-MailboxExportRequest	-Mailbox	kuraw	-FilePath	\\localhost\D$\음료\kuraw.pst
NEW-MailboxExportRequest	-Mailbox	jcshin	-FilePath	\\localhost\D$\음료\jcshin.pst
NEW-MailboxExportRequest	-Mailbox	asg1228	-FilePath	\\localhost\D$\음료\asg1228.pst
NEW-MailboxExportRequest	-Mailbox	asg2392	-FilePath	\\localhost\D$\음료\asg2392.pst
NEW-MailboxExportRequest	-Mailbox	atj007	-FilePath	\\localhost\D$\음료\atj007.pst
NEW-MailboxExportRequest	-Mailbox	ysh1247	-FilePath	\\localhost\D$\음료\ysh1247.pst
NEW-MailboxExportRequest	-Mailbox	bjyae	-FilePath	\\localhost\D$\음료\bjyae.pst
NEW-MailboxExportRequest	-Mailbox	davidoh	-FilePath	\\localhost\D$\음료\davidoh.pst
NEW-MailboxExportRequest	-Mailbox	sswoo5246	-FilePath	\\localhost\D$\음료\sswoo5246.pst
NEW-MailboxExportRequest	-Mailbox	wjm0630	-FilePath	\\localhost\D$\음료\wjm0630.pst
NEW-MailboxExportRequest	-Mailbox	dustwi	-FilePath	\\localhost\D$\음료\dustwi.pst
NEW-MailboxExportRequest	-Mailbox	dhyou	-FilePath	\\localhost\D$\음료\dhyou.pst
NEW-MailboxExportRequest	-Mailbox	blue	-FilePath	\\localhost\D$\음료\blue.pst
NEW-MailboxExportRequest	-Mailbox	wlgh8028	-FilePath	\\localhost\D$\음료\wlgh8028.pst
NEW-MailboxExportRequest	-Mailbox	uto675	-FilePath	\\localhost\D$\음료\uto675.pst
NEW-MailboxExportRequest	-Mailbox	high	-FilePath	\\localhost\D$\음료\high.pst
NEW-MailboxExportRequest	-Mailbox	ycb147	-FilePath	\\localhost\D$\음료\ycb147.pst
NEW-MailboxExportRequest	-Mailbox	djlee	-FilePath	\\localhost\D$\음료\djlee.pst
NEW-MailboxExportRequest	-Mailbox	ldhyun33	-FilePath	\\localhost\D$\음료\ldhyun33.pst
NEW-MailboxExportRequest	-Mailbox	esbin11	-FilePath	\\localhost\D$\음료\esbin11.pst
NEW-MailboxExportRequest	-Mailbox	seungeon	-FilePath	\\localhost\D$\음료\seungeon.pst
NEW-MailboxExportRequest	-Mailbox	sh2lee	-FilePath	\\localhost\D$\음료\sh2lee.pst
NEW-MailboxExportRequest	-Mailbox	cider	-FilePath	\\localhost\D$\음료\cider.pst
NEW-MailboxExportRequest	-Mailbox	20111563	-FilePath	\\localhost\D$\음료\20111563.pst
NEW-MailboxExportRequest	-Mailbox	yhunlee	-FilePath	\\localhost\D$\음료\yhunlee.pst
NEW-MailboxExportRequest	-Mailbox	wglee	-FilePath	\\localhost\D$\음료\wglee.pst
NEW-MailboxExportRequest	-Mailbox	lee30440	-FilePath	\\localhost\D$\음료\lee30440.pst
NEW-MailboxExportRequest	-Mailbox	jglee	-FilePath	\\localhost\D$\음료\jglee.pst
NEW-MailboxExportRequest	-Mailbox	junmin	-FilePath	\\localhost\D$\음료\junmin.pst
NEW-MailboxExportRequest	-Mailbox	krashmir	-FilePath	\\localhost\D$\음료\krashmir.pst
NEW-MailboxExportRequest	-Mailbox	lcm	-FilePath	\\localhost\D$\음료\lcm.pst
NEW-MailboxExportRequest	-Mailbox	skillion	-FilePath	\\localhost\D$\음료\skillion.pst
NEW-MailboxExportRequest	-Mailbox	thhy	-FilePath	\\localhost\D$\음료\thhy.pst
NEW-MailboxExportRequest	-Mailbox	lotte4002	-FilePath	\\localhost\D$\음료\lotte4002.pst
NEW-MailboxExportRequest	-Mailbox	jbim	-FilePath	\\localhost\D$\음료\jbim.pst
NEW-MailboxExportRequest	-Mailbox	hisubi7	-FilePath	\\localhost\D$\음료\hisubi7.pst
NEW-MailboxExportRequest	-Mailbox	jjsw105	-FilePath	\\localhost\D$\음료\jjsw105.pst
NEW-MailboxExportRequest	-Mailbox	jang215	-FilePath	\\localhost\D$\음료\jang215.pst
NEW-MailboxExportRequest	-Mailbox	binghn	-FilePath	\\localhost\D$\음료\binghn.pst
NEW-MailboxExportRequest	-Mailbox	hkj229	-FilePath	\\localhost\D$\음료\hkj229.pst
NEW-MailboxExportRequest	-Mailbox	yhjeon	-FilePath	\\localhost\D$\음료\yhjeon.pst
NEW-MailboxExportRequest	-Mailbox	johnsina2	-FilePath	\\localhost\D$\음료\johnsina2.pst
NEW-MailboxExportRequest	-Mailbox	jungms	-FilePath	\\localhost\D$\음료\jungms.pst
NEW-MailboxExportRequest	-Mailbox	blue30w	-FilePath	\\localhost\D$\음료\blue30w.pst
NEW-MailboxExportRequest	-Mailbox	zeroroad	-FilePath	\\localhost\D$\음료\zeroroad.pst
NEW-MailboxExportRequest	-Mailbox	jyj	-FilePath	\\localhost\D$\음료\jyj.pst
NEW-MailboxExportRequest	-Mailbox	dotheg88	-FilePath	\\localhost\D$\음료\dotheg88.pst
NEW-MailboxExportRequest	-Mailbox	jphyuni	-FilePath	\\localhost\D$\음료\jphyuni.pst
NEW-MailboxExportRequest	-Mailbox	cdh0316	-FilePath	\\localhost\D$\음료\cdh0316.pst
NEW-MailboxExportRequest	-Mailbox	sbjo	-FilePath	\\localhost\D$\음료\sbjo.pst
NEW-MailboxExportRequest	-Mailbox	jojuke	-FilePath	\\localhost\D$\음료\jojuke.pst
NEW-MailboxExportRequest	-Mailbox	jeongin91	-FilePath	\\localhost\D$\음료\jeongin91.pst
NEW-MailboxExportRequest	-Mailbox	chojinyoung	-FilePath	\\localhost\D$\음료\chojinyoung.pst
NEW-MailboxExportRequest	-Mailbox	jinho	-FilePath	\\localhost\D$\음료\jinho.pst
NEW-MailboxExportRequest	-Mailbox	johs	-FilePath	\\localhost\D$\음료\johs.pst
NEW-MailboxExportRequest	-Mailbox	Chaeyosep115	-FilePath	\\localhost\D$\음료\Chaeyosep115.pst
NEW-MailboxExportRequest	-Mailbox	ytchun	-FilePath	\\localhost\D$\음료\ytchun.pst
NEW-MailboxExportRequest	-Mailbox	choilotte	-FilePath	\\localhost\D$\음료\choilotte.pst
NEW-MailboxExportRequest	-Mailbox	cys320	-FilePath	\\localhost\D$\음료\cys320.pst
NEW-MailboxExportRequest	-Mailbox	zingyguy	-FilePath	\\localhost\D$\음료\zingyguy.pst
NEW-MailboxExportRequest	-Mailbox	jychoi7695	-FilePath	\\localhost\D$\음료\jychoi7695.pst
NEW-MailboxExportRequest	-Mailbox	choihs5	-FilePath	\\localhost\D$\음료\choihs5.pst
NEW-MailboxExportRequest	-Mailbox	pjb83	-FilePath	\\localhost\D$\음료\pjb83.pst
NEW-MailboxExportRequest	-Mailbox	ch20071212	-FilePath	\\localhost\D$\음료\ch20071212.pst
NEW-MailboxExportRequest	-Mailbox	hajiung	-FilePath	\\localhost\D$\음료\hajiung.pst
NEW-MailboxExportRequest	-Mailbox	jhha1024	-FilePath	\\localhost\D$\음료\jhha1024.pst
NEW-MailboxExportRequest	-Mailbox	su614	-FilePath	\\localhost\D$\음료\su614.pst
NEW-MailboxExportRequest	-Mailbox	jyhan01	-FilePath	\\localhost\D$\음료\jyhan01.pst
NEW-MailboxExportRequest	-Mailbox	topsecret	-FilePath	\\localhost\D$\음료\topsecret.pst
NEW-MailboxExportRequest	-Mailbox	20150090	-FilePath	\\localhost\D$\음료\20150090.pst
NEW-MailboxExportRequest	-Mailbox	yhuh	-FilePath	\\localhost\D$\음료\yhuh.pst
NEW-MailboxExportRequest	-Mailbox	hong20112156	-FilePath	\\localhost\D$\음료\hong20112156.pst
NEW-MailboxExportRequest	-Mailbox	shwhang	-FilePath	\\localhost\D$\음료\shwhang.pst
NEW-MailboxExportRequest	-Mailbox	youngjin89	-FilePath	\\localhost\D$\음료\youngjin89.pst
NEW-MailboxExportRequest	-Mailbox	hwjwin	-FilePath	\\localhost\D$\음료\hwjwin.pst
NEW-MailboxExportRequest	-Mailbox	stonek1	-FilePath	\\localhost\D$\음료\stonek1.pst
NEW-MailboxExportRequest	-Mailbox	rezaff	-FilePath	\\localhost\D$\음료\rezaff.pst
NEW-MailboxExportRequest	-Mailbox	kimmin0508	-FilePath	\\localhost\D$\음료\kimmin0508.pst
NEW-MailboxExportRequest	-Mailbox	sevileen	-FilePath	\\localhost\D$\음료\sevileen.pst
NEW-MailboxExportRequest	-Mailbox	qjsrns	-FilePath	\\localhost\D$\음료\qjsrns.pst
NEW-MailboxExportRequest	-Mailbox	newgrin	-FilePath	\\localhost\D$\음료\newgrin.pst
NEW-MailboxExportRequest	-Mailbox	aa7115	-FilePath	\\localhost\D$\음료\aa7115.pst
NEW-MailboxExportRequest	-Mailbox	stop2237	-FilePath	\\localhost\D$\음료\stop2237.pst
NEW-MailboxExportRequest	-Mailbox	smilezer	-FilePath	\\localhost\D$\음료\smilezer.pst
NEW-MailboxExportRequest	-Mailbox	shjo	-FilePath	\\localhost\D$\음료\shjo.pst
NEW-MailboxExportRequest	-Mailbox	knchoi	-FilePath	\\localhost\D$\음료\knchoi.pst
NEW-MailboxExportRequest	-Mailbox	ceocms	-FilePath	\\localhost\D$\음료\ceocms.pst
