.$env:exchangeinstallpath\bin\remoteexchange.ps1
connect-exchangeserver -Auto

NEW-MailboxExportRequest -Mailbox	gdkim	-FilePath	\\localhost\D$\주류\gdkim.pst
NEW-MailboxExportRequest -Mailbox	piazza84	-FilePath	\\localhost\D$\주류\piazza84.pst
NEW-MailboxExportRequest -Mailbox	kwanghyunkim	-FilePath	\\localhost\D$\주류\kwanghyunkim.pst
NEW-MailboxExportRequest -Mailbox	kodori	-FilePath	\\localhost\D$\주류\kodori.pst
NEW-MailboxExportRequest -Mailbox	hopesinger	-FilePath	\\localhost\D$\주류\hopesinger.pst
NEW-MailboxExportRequest -Mailbox	genius	-FilePath	\\localhost\D$\주류\genius.pst
NEW-MailboxExportRequest -Mailbox	kkkwon	-FilePath	\\localhost\D$\주류\kkkwon.pst
NEW-MailboxExportRequest -Mailbox	kncmars	-FilePath	\\localhost\D$\주류\kncmars.pst
NEW-MailboxExportRequest -Mailbox	dh.kim	-FilePath	\\localhost\D$\주류\dh.kim.pst
NEW-MailboxExportRequest -Mailbox	dongyoung.kim2	-FilePath	\\localhost\D$\주류\dongyoung.kim2.pst
NEW-MailboxExportRequest -Mailbox	mapsosa	-FilePath	\\localhost\D$\주류\mapsosa.pst
NEW-MailboxExportRequest -Mailbox	kbskw	-FilePath	\\localhost\D$\주류\kbskw.pst
NEW-MailboxExportRequest -Mailbox	kimseonguk21	-FilePath	\\localhost\D$\주류\kimseonguk21.pst
NEW-MailboxExportRequest -Mailbox	6wkim	-FilePath	\\localhost\D$\주류\6wkim.pst
NEW-MailboxExportRequest -Mailbox	lotte0	-FilePath	\\localhost\D$\주류\lotte0.pst
NEW-MailboxExportRequest -Mailbox	ksh4257	-FilePath	\\localhost\D$\주류\ksh4257.pst
NEW-MailboxExportRequest -Mailbox	hyunniy	-FilePath	\\localhost\D$\주류\hyunniy.pst
NEW-MailboxExportRequest -Mailbox	kdeuxist	-FilePath	\\localhost\D$\주류\kdeuxist.pst
NEW-MailboxExportRequest -Mailbox	kimttl	-FilePath	\\localhost\D$\주류\kimttl.pst
NEW-MailboxExportRequest -Mailbox	blacklake87	-FilePath	\\localhost\D$\주류\blacklake87.pst
NEW-MailboxExportRequest -Mailbox	jinhok	-FilePath	\\localhost\D$\주류\jinhok.pst
NEW-MailboxExportRequest -Mailbox	klsj0466	-FilePath	\\localhost\D$\주류\klsj0466.pst
NEW-MailboxExportRequest -Mailbox	taehyun.kim	-FilePath	\\localhost\D$\주류\taehyun.kim.pst
NEW-MailboxExportRequest -Mailbox	hyeonsoo91	-FilePath	\\localhost\D$\주류\hyeonsoo91.pst
NEW-MailboxExportRequest -Mailbox	dooor	-FilePath	\\localhost\D$\주류\dooor.pst
NEW-MailboxExportRequest -Mailbox	hwangjunkim	-FilePath	\\localhost\D$\주류\hwangjunkim.pst
NEW-MailboxExportRequest -Mailbox	khj1022	-FilePath	\\localhost\D$\주류\khj1022.pst
NEW-MailboxExportRequest -Mailbox	dowoori827	-FilePath	\\localhost\D$\주류\dowoori827.pst
NEW-MailboxExportRequest -Mailbox	ygryu	-FilePath	\\localhost\D$\주류\ygryu.pst
NEW-MailboxExportRequest -Mailbox	itsnara	-FilePath	\\localhost\D$\주류\itsnara.pst
NEW-MailboxExportRequest -Mailbox	changyun.min	-FilePath	\\localhost\D$\주류\changyun.min.pst
NEW-MailboxExportRequest -Mailbox	dj.park	-FilePath	\\localhost\D$\주류\dj.park.pst
NEW-MailboxExportRequest -Mailbox	sc.park	-FilePath	\\localhost\D$\주류\sc.park.pst
NEW-MailboxExportRequest -Mailbox	jongkyu.park	-FilePath	\\localhost\D$\주류\jongkyu.park.pst
NEW-MailboxExportRequest -Mailbox	jkchu	-FilePath	\\localhost\D$\주류\jkchu.pst
NEW-MailboxExportRequest -Mailbox	parkcs	-FilePath	\\localhost\D$\주류\parkcs.pst
NEW-MailboxExportRequest -Mailbox	ybaek	-FilePath	\\localhost\D$\주류\ybaek.pst
NEW-MailboxExportRequest -Mailbox	jihunee	-FilePath	\\localhost\D$\주류\jihunee.pst
NEW-MailboxExportRequest -Mailbox	spcall	-FilePath	\\localhost\D$\주류\spcall.pst
NEW-MailboxExportRequest -Mailbox	gssonn	-FilePath	\\localhost\D$\주류\gssonn.pst
NEW-MailboxExportRequest -Mailbox	sim82k	-FilePath	\\localhost\D$\주류\sim82k.pst
NEW-MailboxExportRequest -Mailbox	shimsy	-FilePath	\\localhost\D$\주류\shimsy.pst
NEW-MailboxExportRequest -Mailbox	simson	-FilePath	\\localhost\D$\주류\simson.pst
NEW-MailboxExportRequest -Mailbox	ajiaji	-FilePath	\\localhost\D$\주류\ajiaji.pst
NEW-MailboxExportRequest -Mailbox	ysa2686	-FilePath	\\localhost\D$\주류\ysa2686.pst
NEW-MailboxExportRequest -Mailbox	activeoh	-FilePath	\\localhost\D$\주류\activeoh.pst
NEW-MailboxExportRequest -Mailbox	bsyoo	-FilePath	\\localhost\D$\주류\bsyoo.pst
NEW-MailboxExportRequest -Mailbox	seong	-FilePath	\\localhost\D$\주류\seong.pst
NEW-MailboxExportRequest -Mailbox	yoonbi	-FilePath	\\localhost\D$\주류\yoonbi.pst
NEW-MailboxExportRequest -Mailbox	leenc	-FilePath	\\localhost\D$\주류\leenc.pst
NEW-MailboxExportRequest -Mailbox	nuri.lee	-FilePath	\\localhost\D$\주류\nuri.lee.pst
NEW-MailboxExportRequest -Mailbox	mijin0128	-FilePath	\\localhost\D$\주류\mijin0128.pst
NEW-MailboxExportRequest -Mailbox	lmyj9876	-FilePath	\\localhost\D$\주류\lmyj9876.pst
NEW-MailboxExportRequest -Mailbox	dedalusism	-FilePath	\\localhost\D$\주류\dedalusism.pst
NEW-MailboxExportRequest -Mailbox	HYUNLEE	-FilePath	\\localhost\D$\주류\HYUNLEE.pst
NEW-MailboxExportRequest -Mailbox	soon2210	-FilePath	\\localhost\D$\주류\soon2210.pst
NEW-MailboxExportRequest -Mailbox	nuckino0323	-FilePath	\\localhost\D$\주류\nuckino0323.pst
NEW-MailboxExportRequest -Mailbox	rongs	-FilePath	\\localhost\D$\주류\rongs.pst
NEW-MailboxExportRequest -Mailbox	gksrkdnl	-FilePath	\\localhost\D$\주류\gksrkdnl.pst
NEW-MailboxExportRequest -Mailbox	leeyeshik	-FilePath	\\localhost\D$\주류\leeyeshik.pst
NEW-MailboxExportRequest -Mailbox	yongjiglee	-FilePath	\\localhost\D$\주류\yongjiglee.pst
NEW-MailboxExportRequest -Mailbox	wjlee	-FilePath	\\localhost\D$\주류\wjlee.pst
NEW-MailboxExportRequest -Mailbox	jaeinlee	-FilePath	\\localhost\D$\주류\jaeinlee.pst
NEW-MailboxExportRequest -Mailbox	hagiteja	-FilePath	\\localhost\D$\주류\hagiteja.pst
NEW-MailboxExportRequest -Mailbox	ljyoul	-FilePath	\\localhost\D$\주류\ljyoul.pst
NEW-MailboxExportRequest -Mailbox	sooljunghee	-FilePath	\\localhost\D$\주류\sooljunghee.pst
NEW-MailboxExportRequest -Mailbox	jglee67	-FilePath	\\localhost\D$\주류\jglee67.pst
NEW-MailboxExportRequest -Mailbox	rainman	-FilePath	\\localhost\D$\주류\rainman.pst
NEW-MailboxExportRequest -Mailbox	moodling	-FilePath	\\localhost\D$\주류\moodling.pst
NEW-MailboxExportRequest -Mailbox	prunsan	-FilePath	\\localhost\D$\주류\prunsan.pst
NEW-MailboxExportRequest -Mailbox	jamesho	-FilePath	\\localhost\D$\주류\jamesho.pst
NEW-MailboxExportRequest -Mailbox	sungmooklim	-FilePath	\\localhost\D$\주류\sungmooklim.pst
NEW-MailboxExportRequest -Mailbox	limsc	-FilePath	\\localhost\D$\주류\limsc.pst
NEW-MailboxExportRequest -Mailbox	image	-FilePath	\\localhost\D$\주류\image.pst
NEW-MailboxExportRequest -Mailbox	sbljk1229	-FilePath	\\localhost\D$\주류\sbljk1229.pst
NEW-MailboxExportRequest -Mailbox	limdia	-FilePath	\\localhost\D$\주류\limdia.pst
NEW-MailboxExportRequest -Mailbox	kwangho.jang	-FilePath	\\localhost\D$\주류\kwangho.jang.pst
NEW-MailboxExportRequest -Mailbox	saeromchang	-FilePath	\\localhost\D$\주류\saeromchang.pst
NEW-MailboxExportRequest -Mailbox	wh.jang	-FilePath	\\localhost\D$\주류\wh.jang.pst
NEW-MailboxExportRequest -Mailbox	jjm9978	-FilePath	\\localhost\D$\주류\jjm9978.pst
NEW-MailboxExportRequest -Mailbox	gitaroo325	-FilePath	\\localhost\D$\주류\gitaroo325.pst
NEW-MailboxExportRequest -Mailbox	sejeon	-FilePath	\\localhost\D$\주류\sejeon.pst
NEW-MailboxExportRequest -Mailbox	ellajeon	-FilePath	\\localhost\D$\주류\ellajeon.pst
NEW-MailboxExportRequest -Mailbox	kunhwan.jung	-FilePath	\\localhost\D$\주류\kunhwan.jung.pst
NEW-MailboxExportRequest -Mailbox	gsjoung	-FilePath	\\localhost\D$\주류\gsjoung.pst
NEW-MailboxExportRequest -Mailbox	bbanzile	-FilePath	\\localhost\D$\주류\bbanzile.pst
NEW-MailboxExportRequest -Mailbox	rjung	-FilePath	\\localhost\D$\주류\rjung.pst
NEW-MailboxExportRequest -Mailbox	qhfka14	-FilePath	\\localhost\D$\주류\qhfka14.pst
NEW-MailboxExportRequest -Mailbox	bluesea	-FilePath	\\localhost\D$\주류\bluesea.pst
NEW-MailboxExportRequest -Mailbox	sj.jeong	-FilePath	\\localhost\D$\주류\sj.jeong.pst
NEW-MailboxExportRequest -Mailbox	jwk1	-FilePath	\\localhost\D$\주류\jwk1.pst
NEW-MailboxExportRequest -Mailbox	ycjeong	-FilePath	\\localhost\D$\주류\ycjeong.pst
NEW-MailboxExportRequest -Mailbox	foreverangel	-FilePath	\\localhost\D$\주류\foreverangel.pst
NEW-MailboxExportRequest -Mailbox	gjsrnrns	-FilePath	\\localhost\D$\주류\gjsrnrns.pst
NEW-MailboxExportRequest -Mailbox	hwayings	-FilePath	\\localhost\D$\주류\hwayings.pst
NEW-MailboxExportRequest -Mailbox	kkssh	-FilePath	\\localhost\D$\주류\kkssh.pst
NEW-MailboxExportRequest -Mailbox	illhaeng	-FilePath	\\localhost\D$\주류\illhaeng.pst
NEW-MailboxExportRequest -Mailbox	jccho	-FilePath	\\localhost\D$\주류\jccho.pst
NEW-MailboxExportRequest -Mailbox	kingcph	-FilePath	\\localhost\D$\주류\kingcph.pst
NEW-MailboxExportRequest -Mailbox	jjoosi	-FilePath	\\localhost\D$\주류\jjoosi.pst
NEW-MailboxExportRequest -Mailbox	joohw	-FilePath	\\localhost\D$\주류\joohw.pst
NEW-MailboxExportRequest -Mailbox	aroma202	-FilePath	\\localhost\D$\주류\aroma202.pst
NEW-MailboxExportRequest -Mailbox	ckctg	-FilePath	\\localhost\D$\주류\ckctg.pst
NEW-MailboxExportRequest -Mailbox	circle	-FilePath	\\localhost\D$\주류\circle.pst
NEW-MailboxExportRequest -Mailbox	k2jstar	-FilePath	\\localhost\D$\주류\k2jstar.pst
NEW-MailboxExportRequest -Mailbox	jywin	-FilePath	\\localhost\D$\주류\jywin.pst
NEW-MailboxExportRequest -Mailbox	taewoongchoi	-FilePath	\\localhost\D$\주류\taewoongchoi.pst
NEW-MailboxExportRequest -Mailbox	cmoimin	-FilePath	\\localhost\D$\주류\cmoimin.pst
NEW-MailboxExportRequest -Mailbox	lbhjh	-FilePath	\\localhost\D$\주류\lbhjh.pst
NEW-MailboxExportRequest -Mailbox	yulimhon9	-FilePath	\\localhost\D$\주류\yulimhon9.pst
