
--------------------------------------------------------------------------------
-- 이미지 등록 현황(일자, 부서, 총파일수, 총파일크기(BYTE)
WITH CTE_TEMP (ORG_ID, P_ORG_ID, DEPT_NM, DEPT_PATH, LEVEL, SORT) 
  AS ( 
		SELECT ORG_ID
			 , P_ORG_ID
			 , DEPT_NM
			 , CONVERT(VARCHAR(255), DEPT_NM) DEPT_PATH
			 , 1 AS LEVEL
			 , CONVERT(VARCHAR(255), ORG_ID) SORT
		  FROM XR_ORG_INFO
		 WHERE P_ORG_ID = '00000000'
		 UNION ALL 
		SELECT B.ORG_ID
			 , B.P_ORG_ID
			 , B.DEPT_NM
			 , CONVERT(VARCHAR(255), CONVERT(NVARCHAR(255), CT.DEPT_PATH) + ' > ' + CONVERT(VARCHAR(255), B.DEPT_NM)) DEPT_PATH
			 , LEVEL + 1 AS LEVEL
			 , CONVERT(VARCHAR(255), CONVERT(NVARCHAR(255), CT.SORT) + ' > ' + CONVERT(VARCHAR(255), B.ORG_ID)) SORT 
		FROM XR_ORG_INFO B, CTE_TEMP CT
	   WHERE CT.ORG_ID = B.P_ORG_ID
	 )
SELECT MST.REG_DATE
	 --, MST.ORG_ID
	 , DEPT_NM
	 , DEPT_PATH
	 , TOTAL_COUNT
	 , TOTAL_FILE_SIZE
  FROM (
			SELECT CONVERT(CHAR(10),DI.REG_DATE, 120) REG_DATE
				 , UI.ORG_ID
				 , COUNT(*) TOTAL_COUNT
				 , SUM(FILE_SIZE) TOTAL_FILE_SIZE
			  FROM XR_DOC_INFO DI 
				   LEFT OUTER JOIN XR_USR_INFO UI ON DI.REG_USER_ID = UI.USER_ID
			 WHERE FILE_EXT IN ('jpg', 'jpeg', 'tif', 'tiff','png','gif')
			   AND CONVERT(CHAR(10),DI.REG_DATE, 120) BETWEEN '2018-02-27' AND '2018-02-27' --일자 조회 조건
		  GROUP BY CONVERT(CHAR(10), DI.REG_DATE, 120), ORG_ID
	   ) MST
		 LEFT OUTER JOIN CTE_TEMP CT ON MST.ORG_ID = CT.ORG_ID
ORDER BY REG_DATE ASC, DEPT_PATH;


--------------------------------------------------------------------------------
-- 전자문서 등록 현황(일자, 부서, 총파일수, 총파일크기(BYTE)
WITH CTE_TEMP (ORG_ID, P_ORG_ID, DEPT_NM, DEPT_PATH, LEVEL, SORT) 
  AS (
		SELECT ORG_ID
			 , P_ORG_ID
			 , DEPT_NM
			 , CONVERT(VARCHAR(255), DEPT_NM) DEPT_PATH
			 , 1 AS LEVEL
			 , CONVERT(VARCHAR(255), ORG_ID) SORT
		  FROM XR_ORG_INFO
		 WHERE P_ORG_ID = '00000000'
		 UNION ALL 
		SELECT B.ORG_ID
			 , B.P_ORG_ID
			 , B.DEPT_NM
			 , CONVERT(VARCHAR(255), CONVERT(NVARCHAR(255),CT.DEPT_PATH) + ' > ' + CONVERT(VARCHAR(255), B.DEPT_NM)) DEPT_PATH
			 , LEVEL + 1 AS LEVEL
			 , CONVERT(VARCHAR(255), CONVERT(NVARCHAR(255), CT.SORT) + ' > ' + CONVERT(VARCHAR(255), B.ORG_ID)) SORT 
		FROM XR_ORG_INFO B, CTE_TEMP CT
	   WHERE CT.ORG_ID = B.P_ORG_ID
	 )
SELECT MST.REG_DATE
	 --, MST.ORG_ID
	 , DEPT_NM
	 , DEPT_PATH
	 , TOTAL_COUNT
	 , TOTAL_FILE_SIZE
  FROM (
			SELECT CONVERT(CHAR(10),DI.REG_DATE, 120) REG_DATE
				 , UI.ORG_ID
				 , COUNT(*) TOTAL_COUNT
				 , SUM(FILE_SIZE) TOTAL_FILE_SIZE
			  FROM XR_DOC_INFO DI 
				   LEFT OUTER JOIN XR_USR_INFO UI ON DI.REG_USER_ID = UI.USER_ID
			WHERE FILE_EXT NOT IN ('jpg', 'jpeg', 'tif', 'tiff','png','gif')
			  AND CONVERT(CHAR(10),DI.REG_DATE, 120) BETWEEN '2018-02-27' AND '2018-02-27' --일자 조회 조건
		 GROUP BY CONVERT(CHAR(10), DI.REG_DATE, 120), ORG_ID
	   ) MST
	     LEFT OUTER JOIN CTE_TEMP CT ON MST.ORG_ID = CT.ORG_ID
ORDER BY REG_DATE ASC, DEPT_PATH;
