
USE EAI
-- BC_APPROVALRESULTFI
BEGIN TRAN 

INSERT INTO [dbo].[PROC_MST] (
IF_ID, 
IF_NAME, 
PROJECT_ID, 
START_SUBJECT, 
RUN_MODE ,
FIRST_RUN_TIME,
INTERVAL_UNIT,
INTERVAL,
FILE_YN,
LAST_REMARK,
SOURCE_SYSTEM,
SOURCE_OBJECT,
TARGET_SYSTEM,
TARGET_OBJECT,
ALERT_GROUP,
NOTE,
USE_YN,
REWORK_YN,
CREATE_DTTM,
UPDATE_DTTM ) values
('BC_APPROVALRESULTFI', '전자결재상태 전표용','LT_BC','','NT','','S','5','N',NULL,'EKW3','USP_WPS_DBApproval_D_SELECT;','SAP','ZFI_GW_RESULT','BW_2','','Y','N',getdate(),getdate())


-- BC_APPROVALAUTO
INSERT INTO [dbo].[PROC_MST] (
IF_ID, 
IF_NAME, 
PROJECT_ID, 
START_SUBJECT, 
RUN_MODE ,
FIRST_RUN_TIME,
INTERVAL_UNIT,
INTERVAL,
FILE_YN,
LAST_REMARK,
SOURCE_SYSTEM,
SOURCE_OBJECT,
TARGET_SYSTEM,
TARGET_OBJECT,
ALERT_GROUP,
NOTE,
USE_YN,
REWORK_YN,
CREATE_DTTM,
UPDATE_DTTM ) values
('BC_APPROVALAUTO', '전자결재 호출 AUTO','LT_BC','','SO','','','','N',NULL,'SAP','ZTR_CHEQUE_AUTO','EKW3','http://portal.lottechilsung.co.kr/Service/Interface.asmx?','BW_2','','Y','N',getdate(),getdate())


-- BC_APPROVALLOAD
INSERT INTO [dbo].[PROC_MST] (
IF_ID, 
IF_NAME, 
PROJECT_ID, 
START_SUBJECT, 
RUN_MODE ,
FIRST_RUN_TIME,
INTERVAL_UNIT,
INTERVAL,
FILE_YN,
LAST_REMARK,
SOURCE_SYSTEM,
SOURCE_OBJECT,
TARGET_SYSTEM,
TARGET_OBJECT,
ALERT_GROUP,
NOTE,
USE_YN,
REWORK_YN,
CREATE_DTTM,
UPDATE_DTTM ) values
('BC_APPROVALLOAD', '전자결재 호출 LOAD','LT_BC','','SO','','','','N',NULL,'SAP','ZFI_GW_LOAD','EKW3','http://portal.lottechilsung.co.kr/Service/Interface.asmx?','BW_2','','Y','N',getdate(),getdate())

-- BC_APPROVALREVERSAL
INSERT INTO [dbo].[PROC_MST] (
IF_ID, 
IF_NAME, 
PROJECT_ID, 
START_SUBJECT, 
RUN_MODE ,
FIRST_RUN_TIME,
INTERVAL_UNIT,
INTERVAL,
FILE_YN,
LAST_REMARK,
SOURCE_SYSTEM,
SOURCE_OBJECT,
TARGET_SYSTEM,
TARGET_OBJECT,
ALERT_GROUP,
NOTE,
USE_YN,
REWORK_YN,
CREATE_DTTM,
UPDATE_DTTM ) values
('BC_APPROVALREVERSAL', '전자결재상태 역분개','LT_BC','','SO','','','','N',NULL,'SAP','ZFI_GW_REVERSE','EKW3','http://portal.lottechilsung.co.kr/Service/Interface.asmx?','BW_2','','Y','N',getdate(),getdate())


-- BC_APPROVALDELETE
INSERT INTO [dbo].[PROC_MST] (
IF_ID, 
IF_NAME, 
PROJECT_ID, 
START_SUBJECT, 
RUN_MODE ,
FIRST_RUN_TIME,
INTERVAL_UNIT,
INTERVAL,
FILE_YN,
LAST_REMARK,
SOURCE_SYSTEM,
SOURCE_OBJECT,
TARGET_SYSTEM,
TARGET_OBJECT,
ALERT_GROUP,
NOTE,
USE_YN,
REWORK_YN,
CREATE_DTTM,
UPDATE_DTTM ) values
('BC_APPROVALDELETE', '전자결재상태 삭제','LT_BC','','SO','','','','N',NULL,'SAP','ZFI_GW_DELETE','EKW3','http://portal.lottechilsung.co.kr/Service/Interface.asmx?','BW_2','','Y','N',getdate(),getdate())


-- BC_EVSRESULT
INSERT INTO [dbo].[PROC_MST] (
IF_ID, 
IF_NAME, 
PROJECT_ID, 
START_SUBJECT, 
RUN_MODE ,
FIRST_RUN_TIME,
INTERVAL_UNIT,
INTERVAL,
FILE_YN,
LAST_REMARK,
SOURCE_SYSTEM,
SOURCE_OBJECT,
TARGET_SYSTEM,
TARGET_OBJECT,
ALERT_GROUP,
NOTE,
USE_YN,
REWORK_YN,
CREATE_DTTM,
UPDATE_DTTM ) values
('BC_EVSRESULT', '전자증빙여부값','LT_BC','','NT','','S','10','N',NULL,'EVS','EAI_DOC_KEY_COUNT','EKW3','WF_SLIP_EVS_CNT','BW_2','','Y','N',getdate(),getdate())


