ALTER PROCEDURE SP_TEST04_INSERT
AS
SELECT DeptNm
INTO DeptNm
FROM AvgAmt GROUP BY DeptNm

INSERT INTO E4 SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = '이사대우' 
INSERT INTO S1 SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'S1' 
INSERT INTO S2 SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'S2' 
INSERT INTO M1 SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'M1' 
INSERT INTO M2 SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'M2' 
INSERT INTO SA_M SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'SA(남)' 
INSERT INTO SA_W SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'SA(여)' 
INSERT INTO A_M SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'A(남)' 
INSERT INTO T1 SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'T1(남)' 
INSERT INTO T2 SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'T2(남)' 
INSERT INTO T3 SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'T3(남)' 
INSERT INTO T4 SELECT DeptNm, AvgPayAmt FROM AvgAmt WHERE PgNm = 'T4(남)' 